### ISSUE TITLE
Nice simulation

### ISSUE THREAD

**Issue by xkeksi** [waetrmelon/Acumen#1]
public static float CalculateSlipperinessMultiplier(Player player){
        Material block = player.getLocation().subtract(0, 1, 0).getBlock().getType();
        switch (block){
            case SLIME_BLOCK:
                return 0.8f;
            case ICE:
                return 0.98f;
            case PACKED_ICE:
                return 0.98f;
            case AIR:
                return 1f;
            default:
                return 0.6f;
        }

    }

**Comment by waetrmelon** [comment]
Thanks ig? It's pretty ass, just intended for a test project, Figuring out Movement Mechanics for the first time.

**Comment by xkeksi** [comment]
google a bit, there is a much better way to get the frictions etc
